apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u4hm2s6nz-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-dotnet-basic:482dfa8c6834b5c438b1ef05dd4ac7c72cddf26b@sha256:fa972ce8574f304cdc25273ba27ee7b3ae01a9c210298127a06204c182e3cac1
          name: container-image
